import type { PlayerInput } from "@/lib/types/player";

/** Datos iniciales para poblar MongoDB */
export const SEED_PLAYERS: PlayerInput[] = [
  {
    name: "Matías González",
    category: "Varones Sub 14",
    location: "Santiago, Chile",
    ranking: 12,
    bestNationalRanking: 8,
    regionalRanking: 3,
    wtnSingles: "33.36",
    titlesYear: 2026,
    singlesTitles: 2,
    doublesTitles: 1,
    highlights: [
      "Campeón Copa Futuro 2025",
      "Finalista Nacional Sub-14",
      "Semifinalista Circuito Sur",
    ],
  },
  {
    name: "Valentina Rojas",
    category: "Damas Sub 16",
    location: "Viña del Mar, Chile",
    ranking: 8,
    bestNationalRanking: 6,
    regionalRanking: 1,
    wtnSingles: "30.31",
    titlesYear: 2026,
    singlesTitles: 5,
    doublesTitles: 2,
    highlights: [
      "Campeona Regional 2025",
      "Top 10 Ranking Nacional",
      "MVP Torneo Andes",
    ],
  },
  {
    name: "Diego Muñoz",
    category: "Varones Sub 18",
    location: "Concepción, Chile",
    ranking: 5,
    bestNationalRanking: 4,
    regionalRanking: 2,
    wtnSingles: "28.90",
    titlesYear: 2026,
    singlesTitles: 3,
    doublesTitles: 0,
    highlights: [
      "Campeón Nacional Sub-18",
      "ITF Junior Grade 4",
      "Selección Chilena Juvenil",
    ],
  },
  {
    name: "Camila Soto",
    category: "Damas Sub 14",
    location: "La Serena, Chile",
    ranking: 15,
    regionalRanking: 4,
    highlights: [
      "Finalista Copa Norte",
      "Campeona Dobles Regional",
      "Mejor ranking de temporada",
    ],
  },
  {
    name: "Tomás Herrera",
    category: "Varones Sub 16",
    location: "Temuco, Chile",
    ranking: 11,
    wtnSingles: "Sin registro",
    titlesYear: 2026,
    singlesTitles: 1,
    doublesTitles: 1,
    highlights: [
      "Semifinalista Nacional",
      "Campeón Circuito Sur",
      "Fair Play Award 2025",
    ],
  },
];
